# Generated by Django 5.1.1 on 2025-02-21 12:51

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stored_as', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('file', models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='')),
                ('optimized_image', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.PositiveBigIntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('alt_text', models.TextField()),
                ('retrieval_count', models.PositiveIntegerField(default=0)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
