# Generated by Django 5.1.4 on 2025-03-13 21:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filemodel",
            name="id",
        ),
        migrations.AlterField(
            model_name="filemodel",
            name="stored_as",
            field=models.CharField(
                blank=True,
                default=uuid.uuid4,
                max_length=255,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
