# Generated by Django 5.2.4 on 2025-10-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("icon_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "download_link",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
