# Generated by Django 5.2.4 on 2025-10-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_remove_plan_features_planfeature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planfeature",
            name="description",
        ),
        migrations.AddField(
            model_name="faq",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plan",
            name="billing_period",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("ETB", "ETB"),
                ],
                default="ETB",
                max_length=10,
            ),
        ),
    ]
