# Generated by Django 5.2.4 on 2025-10-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_waitlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
    ]
