# Generated by Django 5.2.4 on 2025-10-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="download",
            name="download_link",
        ),
        migrations.RemoveField(
            model_name="download",
            name="icon_url",
        ),
        migrations.AddField(
            model_name="download",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="downloads/files/"),
        ),
        migrations.AddField(
            model_name="download",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="downloads/icons/"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
