services:
  redis:
    image: redis:alpine
    ports:
      - 6380:6379
  pg:
    image: postgres:alpine
    restart: always
    ports:
      - 5480:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - config/pg.env
    shm_size: 128mb
  app:
    build:
      context: .
    entrypoint: sh entrypoint-app.sh
    depends_on:
      - pg
      - redis
    volumes:
      - medias:/medias
      - static:/static
      - .:/app
    env_file:
      - config/app.env
    ports:
      - 8880:8000
  celery:
    build:
      context: .
    command: celery -A core.celery worker --loglevel=info
    depends_on:
      - pg
      - redis
    volumes:
      - .:/app
    env_file:
      - config/app.env
  celery-beat:
    build:
      context: .
    command: celery -A core.celery beat --loglevel=info
    depends_on:
      - pg
      - redis
    volumes:
      - .:/app
    env_file:
      - config/app.env
  flower:
    build:
      context: .
    command: celery -A core.celery flower --port=5555
    depends_on:
      - redis
      - celery
    volumes:
      - .:/app
    env_file:
      - config/app.env
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_BASIC_AUTH:-admin:admin}
    ports:
      - 5556:5555
volumes:
  medias:
  static:
  pg_data:
