# Generated by Django 5.2.4 on 2025-08-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="conversation_type",
            field=models.CharField(
                choices=[
                    ("direct", "Direct Message"),
                    ("group", "Group Chat"),
                    ("business", "Business"),
                ],
                default="direct",
                max_length=20,
            ),
        ),
    ]
