# Generated by Django 5.1.4 on 2025-03-12 12:12
# flake8: noqa
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format:                     '912345678 / 712345678'. Up to 9 digits allowed.",
                        regex="^(9|7)\\d{8}$",
                    )
                ],
            ),
        ),
    ]
