# Generated by Django 5.1.4 on 2025-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userdevice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phonechangerequest",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="userdevice",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="phonechangerequest",
            name="code",
            field=models.CharField(default="mnbvc", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phonechangerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
