# Generated by Django 5.1.4 on 2025-04-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_employee_branch_role_business_role_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="role_code",
        ),
    ]
