# Generated by Django 5.1.4 on 2025-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_username_user_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="admin_2",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="locality",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="plus_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="sublocality",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
