# Generated by Django 5.1.4 on 2025-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_phonechangerequest_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailchangerequest",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="emailchangerequest",
            name="code",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailchangerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
