# Generated by Django 5.1.4 on 2025-04-22 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_role_role_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="accounts.business",
            ),
        ),
    ]
