# Generated by Django 5.2.4 on 2025-10-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_emailchangerequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevice",
            name="app_build_number",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="app_version",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="app_version_code",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="device_id",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="manufacturer",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="name",
            field=models.CharField(default="unknown", max_length=255),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="os",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
