# Generated by Django 5.1.4 on 2025-04-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_address_admin_2_alter_address_locality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("whole_sale", "Wholesale"),
                    ("manufacturing", "Manufacturing"),
                    ("service", "Service"),
                ],
                max_length=255,
            ),
        ),
        migrations.RemoveField(
            model_name="business",
            name="category",
        ),
        migrations.AddField(
            model_name="business",
            name="category",
            field=models.ManyToManyField(to="accounts.category"),
        ),
    ]
