# Generated by Django 5.1.4 on 2025-04-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_role_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.business",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.business",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="accounts.role",
            ),
        ),
    ]
