# Generated by Django 5.1.4 on 2025-04-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_branch_business_alter_employee_business_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="address",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="address",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="business",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="business",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="business",
            name="category",
        ),
        migrations.RemoveField(
            model_name="business",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="businessactivity",
            name="business",
        ),
        migrations.RemoveField(
            model_name="businessimage",
            name="business",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="business",
        ),
        migrations.RemoveField(
            model_name="role",
            name="business",
        ),
        migrations.RemoveField(
            model_name="businessactivity",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="businessimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="role",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.RemoveField(
            model_name="industry",
            name="image",
        ),
        migrations.RemoveField(
            model_name="role",
            name="permissions",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
