# Generated by Django 5.1.4 on 2025-04-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_business_business_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="plus_code",
            field=models.CharField(blank=True, null=True),
        ),
    ]
