# Generated by Django 5.2.4 on 2026-01-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_userdevice_app_build_number_userdevice_app_version_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailchangerequest",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="phonechangerequest",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="userdevice",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
    ]
