# Generated by Django 5.1.4 on 2025-04-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_address_plus_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
