# Generated by Django 5.1.4 on 2025-04-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_business_address_remove_branch_address_and_more"),
        ("crms", "0003_alter_customer_business"),
        ("financials", "0002_alter_businesspaymentmethod_business"),
        (
            "inventories",
            "0002_alter_pricing_options_alter_supplieditem_options_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Branch",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Business",
        ),
        migrations.DeleteModel(
            name="BusinessActivity",
        ),
        migrations.DeleteModel(
            name="BusinessImage",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Industry",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
