# Generated by Django 5.2.4 on 2026-04-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_emailchangerequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
