# Generated by Django 5.1.4 on 2025-02-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customer_business_supplier_business"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="created_by",
            new_name="owner",
        ),
    ]
