# Generated by Django 5.1.4 on 2025-04-09 13:22

import django.contrib.auth.hashers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_business_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="ResetPasswordRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=255,
                        validators=[django.contrib.auth.hashers.make_password],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
