# Generated by Django 5.1.4 on 2025-04-09 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_password_password_resetpasswordrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetpasswordrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resetpasswordrequest",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="resetpasswordrequest",
            name="code",
            field=models.CharField(max_length=255),
        ),
    ]
