# Generated by Django 5.1.4 on 2025-02-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_employee_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="business",
        ),
        migrations.AddField(
            model_name="employee",
            name="business",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="accounts.business"
            ),
        ),
    ]
