# Generated by Django 5.1.4 on 2025-04-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_verificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="plus_code",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
