# Generated by Django 5.1.4 on 2025-02-19 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0011_remove_employee_business_remove_employee_role_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeebusiness",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="employeeinvitation",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employeeinvitation",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="employeebusiness",
            name="role",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)],
            ),
        ),
        migrations.AlterField(
            model_name="employeeinvitation",
            name="role",
            field=models.CharField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=10
            ),
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
