# Generated by Django 5.1.4 on 2025-02-19 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_employeebusiness_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeebusiness",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hires",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
