# Generated by Django 5.1.4 on 2025-04-24 12:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crms", "0001_initial"),
        ("inventories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="giftcard",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="business",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="redeemed",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="redeemed_at",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="type",
        ),
        migrations.AddField(
            model_name="giftcard",
            name="card_type",
            field=models.CharField(
                choices=[("platform", "Platform"), ("business", "Business")],
                default="business",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="giftcard",
            name="current_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_giftcards",
                to="crms.customer",
            ),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="issued_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issued_giftcards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="products",
            field=models.ManyToManyField(blank=True, to="inventories.item"),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("active", "Active"),
                    ("issued", "issued"),
                    ("redeemed", "redeemed"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="giftcard",
            name="value",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="giftcard",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_giftcards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="giftcard",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GiftCardTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_card_transfer",
                        to="crms.customer",
                    ),
                ),
                (
                    "gift_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_cards",
                        to="crms.giftcard",
                    ),
                ),
                (
                    "to_customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_card_receiver",
                        to="crms.customer",
                    ),
                ),
            ],
        ),
    ]
