# Generated by Django 5.2.4 on 2026-04-28 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0014_add_expires_at_to_employeeinvitation"),
        ("crms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format:                     '912345678 / 712345678'. Up to 9 digits allowed.",
                        regex="^(9|7)\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("email", "business")},
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number__isnull", False)),
                fields=("phone_number", "business"),
                name="unique_phone_number_per_business",
            ),
        ),
    ]
