# Generated by Django 5.2.4 on 2026-06-19 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crms", "0002_customer_unique_per_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
