# Generated by Django 5.1.4 on 2025-04-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
        ("crms", "0002_alter_giftcard_options_remove_giftcard_business_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="business.business"
            ),
        ),
    ]
