# Generated by Django 5.1.4 on 2025-03-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieditem",
            name="item",
            field=models.ManyToManyField(
                related_name="supplied_items", to="inventory.item"
            ),
        ),
    ]
