# Generated by Django 5.1.5 on 2025-02-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufacture",
            new_name="Manufacturer",
        ),
        migrations.AlterModelTable(
            name="manufacturer",
            table="manfacturer",
        ),
    ]
