# Generated by Django 5.1.5 on 2025-02-04 11:49
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_manufacture_manufacturer_and_more"),
    ]

    operations = [
        TrigramExtension(),
    ]
