# Generated by Django 5.1.5 on 2025-02-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_trigram_ext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='manufacture',
            new_name='manufacturer',
        ),
    ]
