# Generated by Django 5.1.4 on 2025-03-11 17:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0018_alter_phonechangerequest_new_phone_alter_user_groups_and_more",
        ),
        ("file", "0001_initial"),
        ("inventory", "0006_supplyreservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.category",
            ),
        ),
        migrations.RemoveField(
            model_name="store",
            name="location",
        ),
        migrations.RemoveField(
            model_name="item",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="returnrecall",
            name="item",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="from_store",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="supply",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="to_store",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="store",
        ),
        migrations.RemoveField(
            model_name="supplyreservation",
            name="supply",
        ),
        migrations.RemoveField(
            model_name="item",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="item",
            name="isvisible",
        ),
        migrations.RemoveField(
            model_name="itemimage",
            name="image_id",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="batch_number",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="expiration_date",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="item",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="man_date",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="sale_price",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="supplier_id",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="unit",
        ),
        migrations.AddField(
            model_name="item",
            name="business",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.business",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="inventory_unit",
            field=models.CharField(default="kg", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="make_online_available",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="selling_quota",
            field=models.PositiveBigIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemimage",
            name="file",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="file.filemodel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supply",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.branch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supply",
            name="name",
            field=models.CharField(default="item", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supply",
            name="recipt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="file.filemodel",
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="supply_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(default="desc"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="is_returnable",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="notify_below",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
            ),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format:                     '912345678 / 712345678'. Up to 9 digits allowed.",
                                regex="^(9|7)\\d{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.business",
                    ),
                ),
            ],
            options={
                "db_table": "supplier",
                "ordering": ["id"],
                "get_latest_by": "id",
            },
        ),
        migrations.CreateModel(
            name="SuppliedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("timestamp", models.DateField(auto_now_add=True)),
                ("discount", models.PositiveIntegerField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.business",
                    ),
                ),
                (
                    "item",
                    models.ManyToManyField(
                        related_name="supplied_items", to="inventory.supply"
                    ),
                ),
                ("supply", models.ManyToManyField(to="inventory.supply")),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "supplied_item",
                "ordering": ["id"],
                "get_latest_by": "id",
            },
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Manufacturer",
        ),
        migrations.DeleteModel(
            name="ReturnRecall",
        ),
        migrations.DeleteModel(
            name="StockMovement",
        ),
        migrations.DeleteModel(
            name="Store",
        ),
        migrations.DeleteModel(
            name="SupplyReservation",
        ),
    ]
