# Generated by Django 5.1.4 on 2025-04-24 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
        ("financials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesspaymentmethod",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to="business.business",
            ),
        ),
    ]
