# Generated by Django 5.1.4 on 2025-07-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesspaymentmethod",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
