# Generated by Django 5.1.4 on 2025-03-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0001_initial"),
        ("inventory", "0007_alter_item_category_remove_store_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="amount",
            new_name="total_left_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="item_id",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.item",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="total_paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction",
                to="financials.order",
            ),
        ),
    ]
