# Generated by Django 5.1.4 on 2025-03-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0002_rename_amount_transaction_total_left_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
    ]
