# Generated by Django 5.1.4 on 2025-04-26 13:16

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0002_alter_businesspaymentmethod_business"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="payment_methods/"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["created_at", "updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="businesspaymentmethod",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.RemoveField(
            model_name="businesspaymentmethod",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="businesspaymentmethod",
            name="identifier",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businesspaymentmethod",
            name="label",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businesspaymentmethod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="businesspaymentmethod",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="financials.paymentmethod",
            ),
        ),
    ]
