# Generated by Django 5.1.4 on 2025-04-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "financials",
            "0003_paymentmethod_alter_businesspaymentmethod_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
    ]
