# Generated by Django 5.1.4 on 2025-03-09 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0003_remove_orderitem_price"),
        ("inventory", "0007_alter_item_category_remove_store_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
            ),
        ),
    ]
