# Generated by Django 5.1.4 on 2025-06-10 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="business.business",
            ),
        ),
    ]
