# Generated by Django 5.1.4 on 2025-04-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="category",
        ),
        migrations.AddField(
            model_name="business",
            name="categories",
            field=models.ManyToManyField(
                related_name="businesses", to="business.category"
            ),
        ),
    ]
