# Generated by Django 5.1.4 on 2025-04-26 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_remove_business_category_business_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="branch",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="business",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="businessactivity",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="industry",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AddField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="businessactivity",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="businessactivity",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
