# Generated by Django 5.1.4 on 2025-06-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_alter_business_address_employeeinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
