# Generated by Django 5.1.4 on 2025-06-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_alter_employeeinvitation_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="branch",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="business",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="businessactivity",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="employeeinvitation",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="industry",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
