# Generated by Django 5.1.4 on 2025-07-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_alter_address_options_alter_branch_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="business",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
