# Generated by Django 5.2.4 on 2025-07-14 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_business_is_active_business_is_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={
                "permissions": [
                    ("can_add_branch", "Can add branch"),
                    ("can_change_branch", "Can change branch"),
                    ("can_delete_branch", "Can delete branch"),
                    ("can_view_branch", "Can view branch"),
                    ("can_add_employee", "Can add employee"),
                    ("can_change_employee", "Can change employee"),
                    ("can_delete_employee", "Can delete employee"),
                    ("can_view_employee", "Can view employee"),
                    ("can_add_address", "Can add address"),
                    ("can_change_address", "Can change address"),
                    ("can_delete_address", "Can delete address"),
                    ("can_view_address", "Can view address"),
                    ("can_add_employeeinvitation", "Can add employee invitation"),
                    ("can_change_employeeinvitation", "Can change employee invitation"),
                    ("can_delete_employeeinvitation", "Can delete employee invitation"),
                    ("can_view_employeeinvitation", "Can view employee invitation"),
                    ("can_add_group", "Can add group"),
                    ("can_change_group", "Can change group"),
                    ("can_delete_group", "Can delete group"),
                    ("can_view_group", "Can view group"),
                    ("can_add_order", "Can add order"),
                    ("can_change_order", "Can change order"),
                    ("can_delete_order", "Can delete order"),
                    ("can_view_order", "Can view order"),
                    ("can_add_item", "Can add item"),
                    ("can_change_item", "Can change item"),
                    ("can_delete_item", "Can delete item"),
                    ("can_view_item", "Can view item"),
                    ("can_add_inventorymovement", "Can add inventory movement"),
                    ("can_change_inventorymovement", "Can change inventory movement"),
                    ("can_delete_inventorymovement", "Can delete inventory movement"),
                    ("can_view_inventorymovement", "Can view inventory movement"),
                    ("can_add_inventory", "Can add inventory"),
                    ("can_change_inventory", "Can change inventory"),
                    ("can_delete_inventory", "Can delete inventory"),
                    ("can_view_inventory", "Can view inventory"),
                    ("can_add_property", "Can add property"),
                    ("can_change_property", "Can change property"),
                    ("can_delete_property", "Can delete property"),
                    ("can_view_property", "Can view property"),
                    ("can_add_itemvariant", "Can add item variant"),
                    ("can_change_itemvariant", "Can change item variant"),
                    ("can_delete_itemvariant", "Can delete item variant"),
                    ("can_view_itemvariant", "Can view item variant"),
                    ("can_add_supplier", "Can add supplier"),
                    ("can_change_supplier", "Can change supplier"),
                    ("can_delete_supplier", "Can delete supplier"),
                    ("can_view_supplier", "Can view supplier"),
                    ("can_add_customer", "Can add customer"),
                    ("can_change_customer", "Can change customer"),
                    ("can_delete_customer", "Can delete customer"),
                    ("can_view_customer", "Can view customer"),
                    (
                        "can_add_businesspaymentmethod",
                        "Can add business payment method",
                    ),
                    (
                        "can_change_businesspaymentmethod",
                        "Can change business payment method",
                    ),
                    (
                        "can_delete_businesspaymentmethod",
                        "Can delete business payment method",
                    ),
                    (
                        "can_view_businesspaymentmethod",
                        "Can view business payment method",
                    ),
                    ("can_add_transaction", "Can add transaction"),
                    ("can_change_transaction", "Can change transaction"),
                    ("can_delete_transaction", "Can delete transaction"),
                    ("can_view_transaction", "Can view transaction"),
                    ("can_add_giftcard", "Can add gift card"),
                    ("can_change_giftcard", "Can change gift card"),
                    ("can_delete_giftcard", "Can delete gift card"),
                    ("can_view_giftcard", "Can view gift card"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="business.branch",
            ),
        ),
    ]
