# Generated by Django 5.2.4 on 2025-07-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0007_alter_business_options_alter_employee_branch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={
                "permissions": [
                    ("can_add_branch_business", "Can add branch"),
                    ("can_change_branch_business", "Can change branch"),
                    ("can_delete_branch_business", "Can delete branch"),
                    ("can_view_branch_business", "Can view branch"),
                    ("can_add_employee_business", "Can add employee"),
                    ("can_change_employee_business", "Can change employee"),
                    ("can_delete_employee_business", "Can delete employee"),
                    ("can_view_employee_business", "Can view employee"),
                    ("can_add_address_business", "Can add address"),
                    ("can_change_address_business", "Can change address"),
                    ("can_delete_address_business", "Can delete address"),
                    ("can_view_address_business", "Can view address"),
                    (
                        "can_add_employeeinvitation_business",
                        "Can add employee invitation",
                    ),
                    (
                        "can_change_employeeinvitation_business",
                        "Can change employee invitation",
                    ),
                    (
                        "can_delete_employeeinvitation_business",
                        "Can delete employee invitation",
                    ),
                    (
                        "can_view_employeeinvitation_business",
                        "Can view employee invitation",
                    ),
                    ("can_add_group_business", "Can add group"),
                    ("can_change_group_business", "Can change group"),
                    ("can_delete_group_business", "Can delete group"),
                    ("can_view_group_business", "Can view group"),
                    ("can_add_order_business", "Can add order"),
                    ("can_change_order_business", "Can change order"),
                    ("can_delete_order_business", "Can delete order"),
                    ("can_view_order_business", "Can view order"),
                    ("can_add_item_business", "Can add item"),
                    ("can_change_item_business", "Can change item"),
                    ("can_delete_item_business", "Can delete item"),
                    ("can_view_item_business", "Can view item"),
                    (
                        "can_add_inventorymovement_business",
                        "Can add inventory movement",
                    ),
                    (
                        "can_change_inventorymovement_business",
                        "Can change inventory movement",
                    ),
                    (
                        "can_delete_inventorymovement_business",
                        "Can delete inventory movement",
                    ),
                    (
                        "can_view_inventorymovement_business",
                        "Can view inventory movement",
                    ),
                    ("can_add_inventory_business", "Can add inventory"),
                    ("can_change_inventory_business", "Can change inventory"),
                    ("can_delete_inventory_business", "Can delete inventory"),
                    ("can_view_inventory_business", "Can view inventory"),
                    ("can_add_property_business", "Can add property"),
                    ("can_change_property_business", "Can change property"),
                    ("can_delete_property_business", "Can delete property"),
                    ("can_view_property_business", "Can view property"),
                    ("can_add_itemvariant_business", "Can add item variant"),
                    ("can_change_itemvariant_business", "Can change item variant"),
                    ("can_delete_itemvariant_business", "Can delete item variant"),
                    ("can_view_itemvariant_business", "Can view item variant"),
                    ("can_add_supplier_business", "Can add supplier"),
                    ("can_change_supplier_business", "Can change supplier"),
                    ("can_delete_supplier_business", "Can delete supplier"),
                    ("can_view_supplier_business", "Can view supplier"),
                    ("can_add_customer_business", "Can add customer"),
                    ("can_change_customer_business", "Can change customer"),
                    ("can_delete_customer_business", "Can delete customer"),
                    ("can_view_customer_business", "Can view customer"),
                    (
                        "can_add_businesspaymentmethod_business",
                        "Can add business payment method",
                    ),
                    (
                        "can_change_businesspaymentmethod_business",
                        "Can change business payment method",
                    ),
                    (
                        "can_delete_businesspaymentmethod_business",
                        "Can delete business payment method",
                    ),
                    (
                        "can_view_businesspaymentmethod_business",
                        "Can view business payment method",
                    ),
                    ("can_add_transaction_business", "Can add transaction"),
                    ("can_change_transaction_business", "Can change transaction"),
                    ("can_delete_transaction_business", "Can delete transaction"),
                    ("can_view_transaction_business", "Can view transaction"),
                    ("can_add_giftcard_business", "Can add gift card"),
                    ("can_change_giftcard_business", "Can change gift card"),
                    ("can_delete_giftcard_business", "Can delete gift card"),
                    ("can_view_giftcard_business", "Can view gift card"),
                ]
            },
        ),
    ]
