# Generated by Django 5.2.4 on 2025-07-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0008_alter_business_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "permissions": [
                    ("can_add_branch_branch", "Can add branch"),
                    ("can_change_branch_branch", "Can change branch"),
                    ("can_delete_branch_branch", "Can delete branch"),
                    ("can_view_branch_branch", "Can view branch"),
                    ("can_add_employee_branch", "Can add employee"),
                    ("can_change_employee_branch", "Can change employee"),
                    ("can_delete_employee_branch", "Can delete employee"),
                    ("can_view_employee_branch", "Can view employee"),
                    ("can_add_address_branch", "Can add address"),
                    ("can_change_address_branch", "Can change address"),
                    ("can_delete_address_branch", "Can delete address"),
                    ("can_view_address_branch", "Can view address"),
                    (
                        "can_add_employeeinvitation_branch",
                        "Can add employee invitation",
                    ),
                    (
                        "can_change_employeeinvitation_branch",
                        "Can change employee invitation",
                    ),
                    (
                        "can_delete_employeeinvitation_branch",
                        "Can delete employee invitation",
                    ),
                    (
                        "can_view_employeeinvitation_branch",
                        "Can view employee invitation",
                    ),
                    ("can_add_group_branch", "Can add group"),
                    ("can_change_group_branch", "Can change group"),
                    ("can_delete_group_branch", "Can delete group"),
                    ("can_view_group_branch", "Can view group"),
                    ("can_add_order_branch", "Can add order"),
                    ("can_change_order_branch", "Can change order"),
                    ("can_delete_order_branch", "Can delete order"),
                    ("can_view_order_branch", "Can view order"),
                    ("can_add_item_branch", "Can add item"),
                    ("can_change_item_branch", "Can change item"),
                    ("can_delete_item_branch", "Can delete item"),
                    ("can_view_item_branch", "Can view item"),
                    ("can_add_inventorymovement_branch", "Can add inventory movement"),
                    (
                        "can_change_inventorymovement_branch",
                        "Can change inventory movement",
                    ),
                    (
                        "can_delete_inventorymovement_branch",
                        "Can delete inventory movement",
                    ),
                    (
                        "can_view_inventorymovement_branch",
                        "Can view inventory movement",
                    ),
                    ("can_add_inventory_branch", "Can add inventory"),
                    ("can_change_inventory_branch", "Can change inventory"),
                    ("can_delete_inventory_branch", "Can delete inventory"),
                    ("can_view_inventory_branch", "Can view inventory"),
                    ("can_add_property_branch", "Can add property"),
                    ("can_change_property_branch", "Can change property"),
                    ("can_delete_property_branch", "Can delete property"),
                    ("can_view_property_branch", "Can view property"),
                    ("can_add_itemvariant_branch", "Can add item variant"),
                    ("can_change_itemvariant_branch", "Can change item variant"),
                    ("can_delete_itemvariant_branch", "Can delete item variant"),
                    ("can_view_itemvariant_branch", "Can view item variant"),
                    ("can_add_supplier_branch", "Can add supplier"),
                    ("can_change_supplier_branch", "Can change supplier"),
                    ("can_delete_supplier_branch", "Can delete supplier"),
                    ("can_view_supplier_branch", "Can view supplier"),
                    ("can_add_customer_branch", "Can add customer"),
                    ("can_change_customer_branch", "Can change customer"),
                    ("can_delete_customer_branch", "Can delete customer"),
                    ("can_view_customer_branch", "Can view customer"),
                    (
                        "can_add_businesspaymentmethod_branch",
                        "Can add business payment method",
                    ),
                    (
                        "can_change_businesspaymentmethod_branch",
                        "Can change business payment method",
                    ),
                    (
                        "can_delete_businesspaymentmethod_branch",
                        "Can delete business payment method",
                    ),
                    (
                        "can_view_businesspaymentmethod_branch",
                        "Can view business payment method",
                    ),
                    ("can_add_transaction_branch", "Can add transaction"),
                    ("can_change_transaction_branch", "Can change transaction"),
                    ("can_delete_transaction_branch", "Can delete transaction"),
                    ("can_view_transaction_branch", "Can view transaction"),
                    ("can_add_giftcard_branch", "Can add gift card"),
                    ("can_change_giftcard_branch", "Can change gift card"),
                    ("can_delete_giftcard_branch", "Can delete gift card"),
                    ("can_view_giftcard_branch", "Can view gift card"),
                ]
            },
        ),
    ]
