# Generated by Django 5.2.4 on 2025-07-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0009_alter_branch_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("Owner", "Owner"),
                    ("Employee", "Employee"),
                    ("Business admin", "Business Admin"),
                    ("Branch manager", "Branch Manager"),
                ],
                max_length=255,
            ),
        ),
    ]
