# Generated by Django 5.2.4 on 2025-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0010_alter_role_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("employee", "Employee"),
                    ("business_admin", "Business admin"),
                    ("branch_manager", "Branch manager"),
                ],
                max_length=255,
            ),
        ),
    ]
