# Generated by Django 5.2.4 on 2026-01-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_alter_branch_options_alter_business_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="businessactivity",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="employeeinvitation",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="industry",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
    ]
