# Generated by Django 5.2.4 on 2026-04-14 13:56

from django.db import migrations, models

import business.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0013_alter_address_options_alter_businessactivity_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeinvitation",
            name="expires_at",
            field=models.DateTimeField(
                default=business.models.default_invitation_expiry
            ),
        ),
    ]
