# Generated by Django 5.2.4 on 2026-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0015_alter_branch_options_alter_business_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeinvitation",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
