# Generated by Django 5.2.4 on 2026-06-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0015_alter_branch_options_alter_business_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
