# Generated by Django 5.1.4 on 2025-03-11 16:54
# flake8: noqa
import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format:                     '912345678 / 712345678'. Up to 9 digits allowed.",
                        regex="^(9|7)\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="giftcard",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
