# Generated by Django 5.1.4 on 2025-04-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GiftCard",
        ),
    ]
