# Generated by Django 5.1.4 on 2025-04-11 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_giftcard_options_customer_created_at_and_more"),
        ("financials", "0003_businesspaymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcardtransaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gift_card_transactions",
                to="financials.order",
            ),
        ),
    ]
