# Generated by Django 5.1.4 on 2025-04-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_giftcardtransaction_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcardtransaction",
            name="order",
        ),
    ]
