# Generated by Django 5.1.4 on 2025-04-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileMeta",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("public_url", models.CharField(max_length=255)),
            ],
        ),
    ]
