# Generated by Django 5.2.4 on 2025-10-13 02:05

import files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=files.models.FileModel.upload_to)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("PROFILE_PICTURE", "Profile Picture"),
                            ("ITEM", "Item"),
                            ("RECEIPT", "Receipt"),
                            ("CHAT", "Chat"),
                            ("REPORT", "Report"),
                            ("INVOICE", "Invoice"),
                            ("OTHER", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
