# Generated by Django 5.2.4 on 2026-01-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_filemodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filemodel",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
    ]
