# Generated by Django 5.2.4 on 2026-04-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_filemodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemodel",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Image"),
                    ("DOCUMENT", "Document"),
                    ("VIDEO", "Video"),
                    ("AUDIO", "Audio"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
