# Generated by Django 5.1.4 on 2025-04-24 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
        ("files", "0001_initial"),
        ("inventories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricing",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="supplieditem",
            options={"get_latest_by": "id", "ordering": ["created_at", "updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"get_latest_by": "id", "ordering": ["created_at", "updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="supply",
            options={"get_latest_by": "id", "ordering": ["created_at", "updated_at"]},
        ),
        migrations.RenameField(
            model_name="supply",
            old_name="supply_date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="supply",
            old_name="name",
            new_name="label",
        ),
        migrations.AddField(
            model_name="itemimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itemimage",
            name="is_thumbnail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itemimage",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="itemimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="supply",
            name="supplied_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supply",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="business.business"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="business.category"
            ),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="files.filemeta"
            ),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventories.item"
            ),
        ),
        migrations.AlterField(
            model_name="supplieditem",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="business.business"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="business.business"
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="business.branch"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supply",
            unique_together={("label", "branch")},
        ),
    ]
