# Generated by Django 5.1.4 on 2025-06-16 14:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_alter_address_options_alter_branch_options_and_more"),
        ("inventories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="itemimage",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="itemvariant",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="pricing",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="property",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="returnrecall",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="supplieditem",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("movement_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("shipped", "Shipped"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.business",
                    ),
                ),
                (
                    "from_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_movements",
                        to="business.branch",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipped_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_movements",
                        to="business.branch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovementItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_requested", models.PositiveIntegerField()),
                ("quantity_shipped", models.PositiveIntegerField(default=0)),
                ("quantity_received", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movement_items",
                        to="inventories.inventorymovement",
                    ),
                ),
                (
                    "supplied_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventories.supplieditem",
                    ),
                ),
            ],
            options={
                "unique_together": {("movement", "supplied_item")},
            },
        ),
    ]
