# Generated by Django 5.2.4 on 2025-08-03 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0002_alter_item_options_alter_itemimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplieditem",
            name="variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplied_items",
                to="inventories.itemvariant",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplieditem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplied_items",
                to="inventories.item",
            ),
        ),
    ]
