# Generated by Django 5.1.4 on 2025-04-26 08:01

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
        (
            "inventories",
            "0002_alter_pricing_options_alter_supplieditem_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemimage",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="supplieditem",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="supply",
            options={},
        ),
        migrations.RenameField(
            model_name="pricing",
            old_name="min_quantity",
            new_name="min_selling_quota",
        ),
        migrations.RenameField(
            model_name="supplieditem",
            old_name="barcode",
            new_name="product_number",
        ),
        migrations.RenameField(
            model_name="supplieditem",
            old_name="price",
            new_name="purchase_price",
        ),
        migrations.RemoveField(
            model_name="supplieditem",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="supplieditem",
            name="expiry_date",
        ),
        migrations.RemoveField(
            model_name="supplieditem",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="recipt",
        ),
        migrations.RemoveField(
            model_name="supply",
            name="supplied_date",
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="expire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="supplieditem",
            name="item",
        ),
        migrations.AlterField(
            model_name="supplieditem",
            name="man_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="supplieditem",
            name="supply",
        ),
        migrations.AlterModelTable(
            name="item",
            table=None,
        ),
        migrations.AlterModelTable(
            name="itemimage",
            table=None,
        ),
        migrations.AlterModelTable(
            name="pricing",
            table=None,
        ),
        migrations.AlterModelTable(
            name="supplieditem",
            table=None,
        ),
        migrations.AlterModelTable(
            name="supplier",
            table=None,
        ),
        migrations.AlterModelTable(
            name="supply",
            table=None,
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="business.business",
                    ),
                ),
            ],
            options={
                "db_table": "group",
                "ordering": ["created_at", "updated_at"],
                "get_latest_by": "created_at",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventories.group",
            ),
        ),
        migrations.CreateModel(
            name="ItemVariant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("batch_number", models.CharField(max_length=255)),
                ("product_number", models.CharField(max_length=255, unique=True)),
                ("expire_date", models.DateField(blank=True, null=True)),
                ("man_date", models.DateField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_returnable", models.BooleanField(default=False)),
                ("is_visible_online", models.BooleanField(default=True)),
                ("receive_online_orders", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.business",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="inventories.item",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventories.supplier",
                    ),
                ),
                (
                    "supply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="inventories.supply",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="pricing",
            name="item_variant",
            field=models.ForeignKey(
                #
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricings",
                to="inventories.itemvariant",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "item_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="inventories.itemvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReturnRecall",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "item_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventories.itemvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="item",
            field=models.ForeignKey(
                #
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplied_items",
                to="inventories.item",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="supply",
            field=models.ForeignKey(
                #
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplied_items",
                to="inventories.supply",
            ),
            preserve_default=False,
        ),
    ]
