# Generated by Django 5.1.4 on 2025-04-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventories",
            "0003_alter_itemimage_options_alter_supplieditem_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemvariant",
            name="business",
        ),
    ]
