# Generated by Django 5.2.4 on 2025-08-03 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financials", "0002_alter_businesspaymentmethod_options_and_more"),
        ("inventories", "0003_supplieditem_variant_alter_supplieditem_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplieditem",
            name="supplier",
        ),
        migrations.AddField(
            model_name="supply",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplies",
                to="financials.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="supply",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplies",
                to="inventories.supplier",
            ),
        ),
    ]
