# Generated by Django 5.2.4 on 2025-08-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventories",
            "0004_remove_supplieditem_supplier_supply_payment_method_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemvariant",
            name="batch_number",
        ),
    ]
