# Generated by Django 5.1.4 on 2025-04-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0004_remove_itemvariant_business"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemvariant",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="supply",
        ),
    ]
