# Generated by Django 5.1.4 on 2025-04-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0005_remove_itemvariant_supplier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemvariant",
            old_name="product_number",
            new_name="sku",
        ),
    ]
