# Generated by Django 5.2.4 on 2025-08-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0010_alter_role_role_name"),
        ("inventories", "0005_remove_itemvariant_batch_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="branch",
            field=models.ForeignKey(
                default="f0c5ed02-ccce-4665-93a1-73c4295e5c1a",
                on_delete=django.db.models.deletion.CASCADE,
                to="business.branch",
            ),
            preserve_default=False,
        ),
    ]
