# Generated by Django 5.1.4 on 2025-04-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0006_rename_product_number_itemvariant_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="is_returnable",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_visible_online",
        ),
        migrations.RemoveField(
            model_name="item",
            name="notify_below",
        ),
        migrations.RemoveField(
            model_name="item",
            name="receive_online_orders",
        ),
        migrations.AddField(
            model_name="itemvariant",
            name="notify_below",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
