# Generated by Django 5.2.4 on 2025-08-06 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0006_item_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymovementitem",
            name="variant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventories.itemvariant",
            ),
            preserve_default=False,
        ),
    ]
