# Generated by Django 5.2.4 on 2025-08-08 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0007_inventorymovementitem_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemvariant",
            name="expire_date",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="is_returnable",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="is_visible_online",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="man_date",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="notify_below",
        ),
        migrations.RemoveField(
            model_name="itemvariant",
            name="receive_online_orders",
        ),
        migrations.AddField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="is_returnable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="is_visible_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="notify_below",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="receive_online_orders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="is_returnable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="is_visible_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="notify_below",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemvariant",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="itemvariant",
            name="selling_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
