# Generated by Django 5.2.4 on 2025-08-10 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0011_alter_role_role_name"),
        ("inventories", "0008_remove_itemvariant_expire_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.business",
            ),
        ),
    ]
