# Generated by Django 5.2.4 on 2025-08-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0009_supply_business"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "Property", "verbose_name_plural": "Properties"},
        ),
        migrations.AlterModelOptions(
            name="supply",
            options={"verbose_name": "Supply", "verbose_name_plural": "Supplies"},
        ),
        migrations.AddField(
            model_name="supplieditem",
            name="initial_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
