# Generated by Django 5.2.4 on 2025-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0010_alter_property_options_alter_supply_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieditem",
            name="product_number",
            field=models.CharField(max_length=255),
        ),
    ]
