# Generated by Django 5.2.4 on 2025-10-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_alter_businesspaymentmethod_options_and_more"),
        ("inventories", "0011_alter_supplieditem_product_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supply",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplies",
                to="finances.businesspaymentmethod",
            ),
        ),
    ]
