# Generated by Django 5.2.4 on 2025-10-06 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0012_alter_supply_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="supply",
            name="no_of_items",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supply",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
    ]
