# Generated by Django 5.2.4 on 2025-10-06 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0013_supply_no_of_items_supply_total_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supply",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
