# Generated by Django 5.2.4 on 2026-01-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0015_itemvideo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="itemimage",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="itemvariant",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="pricing",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="returnrecall",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="supplieditem",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.DeleteModel(
            name="ItemVideo",
        ),
    ]
