# Generated by Django 5.2.4 on 2026-01-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0016_alter_item_options_alter_itemimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemvariant",
            name="sku",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
