# Generated by Django 5.2.4 on 2026-05-21 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0015_alter_branch_options_alter_business_options"),
        ("inventories", "0020_make_supplier_email_optional"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={},
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format:                     '912345678 / 712345678'. Up to 9 digits allowed.",
                        regex="^(9|7)\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supply",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number__isnull", False)),
                fields=("phone_number", "business"),
                name="unique_supplier_phone_number_per_business",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name__isnull", False)),
                fields=("name", "business"),
                name="unique_supplier_name_per_business",
            ),
        ),
    ]
