# Generated by Django 5.2.4 on 2026-06-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventories",
            "0021_alter_supplier_options_alter_supplier_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
    ]
