# Generated by Django 5.2.4 on 2026-06-06 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_filemodel_file_type"),
        ("inventories", "0022_remove_item_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="files.filemeta"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemvideo_set",
                        to="inventories.item",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "-updated_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
