# Generated by Django 5.2.4 on 2026-06-18 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0022_remove_item_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplieditem",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
