# Generated by Django 5.2.4 on 2026-06-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0023_alter_supplieditem_purchase_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemvariant",
            name="selling_price",
        ),
    ]
