# Generated by Django 5.2.4 on 2025-10-08 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_alter_branch_options_alter_business_options"),
        ("finances", "0002_alter_businesspaymentmethod_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesspaymentmethod",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to="business.branch",
            ),
        ),
    ]
