# Generated by Django 5.2.4 on 2025-10-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_alter_branch_options_alter_business_options"),
        ("finances", "0003_businesspaymentmethod_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="total_left_amount",
        ),
        migrations.AddField(
            model_name="transaction",
            name="branch",
            field=models.ForeignKey(
                default="3fa85f64-5717-4562-b3fc-2c963f66afa6",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="business.branch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="business",
            field=models.ForeignKey(
                default="3fa85f64-5717-4562-b3fc-2c963f66afa6",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="business.business",
            ),
            preserve_default=False,
        ),
    ]
