# Generated by Django 5.2.4 on 2025-10-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0005_transaction_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="total_left_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
