# Generated by Django 5.2.4 on 2026-01-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0006_transaction_total_left_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesspaymentmethod",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
    ]
