# Generated by Django 5.2.4 on 2026-05-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0014_add_expires_at_to_employeeinvitation"),
        ("finances", "0009_transaction_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesspaymentmethod",
            options={},
        ),
        migrations.AlterField(
            model_name="businesspaymentmethod",
            name="identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="businesspaymentmethod",
            unique_together={("business", "branch", "identifier")},
        ),
    ]
