# Generated by Django 5.2.4 on 2026-05-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0010_alter_businesspaymentmethod_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("SALE", "Sale"),
                    ("SERVICE_REVENUE", "Service Revenue"),
                    ("OTHER_INCOME", "Other Income"),
                    ("EXPENSE", "Expense"),
                    ("RENT", "Rent"),
                    ("SALARY", "Salary"),
                    ("UTILITY", "Utility"),
                    ("PURCHASE", "Purchase"),
                    ("MAINTENANCE", "Maintenance"),
                    ("OTHER_EXPENSE", "Other Expense"),
                    ("DEBT", "Debt"),
                    ("REFUND", "Refund"),
                ],
                max_length=20,
            ),
        ),
    ]
