# Generated by Django 5.2.4 on 2026-05-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0011_alter_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesspaymentmethod",
            name="receiver_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
