# Generated by Django 5.2.4 on 2026-05-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0012_businesspaymentmethod_receiver_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="total_left_amount",
        ),
    ]
