# Generated by Django 5.2.4 on 2025-10-06 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_alter_branch_options_alter_business_options"),
        ("crms", "0001_initial"),
        ("inventories", "0014_alter_supply_total_cost"),
        ("orders", "0002_alter_order_options_alter_orderitem_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="item",
        ),
        migrations.AddField(
            model_name="order",
            name="additional_info",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                default="3fa85f64-5717-4562-b3fc-2c963f66afa6",
                on_delete=django.db.models.deletion.CASCADE,
                to="business.branch",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="business",
            field=models.ForeignKey(
                default="3fa85f64-5717-4562-b3fc-2c963f66afa6",
                on_delete=django.db.models.deletion.CASCADE,
                to="business.business",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                default="3fa85f64-5717-4562-b3fc-2c963f66afa6",
                on_delete=django.db.models.deletion.CASCADE,
                to="crms.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="employee",
            field=models.ForeignKey(
                default="3fa85f64-5717-4562-b3fc-2c963f66afa6",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                default="3fa85f64-5717-4562-b3fc-2c963f66afa6",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventories.itemvariant",
            ),
            preserve_default=False,
        ),
    ]
