# Generated by Django 5.2.4 on 2025-10-06 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_alter_businesspaymentmethod_options_and_more"),
        ("orders", "0003_remove_order_customer_id_remove_order_employee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                default="3fa85f64-5717-4562-b3fc-2c963f66afa6",
                on_delete=django.db.models.deletion.CASCADE,
                to="finances.businesspaymentmethod",
            ),
            preserve_default=False,
        ),
    ]
