# Generated by Django 5.2.4 on 2025-10-08 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_alter_branch_options_alter_business_options"),
        ("orders", "0005_alter_order_customer_alter_order_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business.employee",
            ),
        ),
    ]
