# Generated by Django 5.2.4 on 2026-01-07 12:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_alter_branch_options_alter_business_options"),
        ("orders", "0006_alter_order_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("CONFIRMED", "Confirmed"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                    ("PAID", "Paid"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                    ("RETURNED", "Returned"),
                ],
                default="PROCESSING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field_name",
                    models.CharField(
                        help_text="Name of the field that was changed", max_length=100
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, help_text="Previous value of the field", null=True
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, help_text="New value of the field", null=True
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason for the change",
                        null=True,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "changed_by_employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_changes",
                        to="business.employee",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"],
                        name="order_histo_order_i_4442d1_idx",
                    ),
                    models.Index(
                        fields=["field_name"], name="order_histo_field_n_c6ebe5_idx"
                    ),
                ],
            },
        ),
    ]
