# Generated by Django 5.2.4 on 2026-01-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_status_orderhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "get_latest_by": "created_at",
                "ordering": ["created_at", "-updated_at"],
            },
        ),
    ]
