# Generated by Django 5.2.4 on 2026-05-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_add_orderreturn_orderreturnitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
