# Generated by Django 5.2.4 on 2026-05-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0010_alter_businesspaymentmethod_options_and_more"),
        ("orders", "0010_add_price_to_orderitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("payment_method", "transaction_id")},
        ),
    ]
