# Generated by Django 5.2.4 on 2026-05-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventories", "0020_make_supplier_email_optional"),
        ("orders", "0011_alter_order_options_order_transaction_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="supplied_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventories.supplieditem",
            ),
        ),
    ]
