# Generated by Django 5.2.4 on 2026-04-15 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0014_add_expires_at_to_employeeinvitation"),
        ("notifications", "0002_alter_notification_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="business.business",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("low_stock", "Low Stock Alert"),
                    ("price_change", "Price Change"),
                    ("product_updated", "Product Updated"),
                    ("restocked", "Restocked"),
                    ("order_completed", "Order Completed"),
                    ("inventory_movement", "Inventory Movement"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("push", "Push"),
                    ("sms", "SMS"),
                    ("all", "All"),
                ],
                default="push",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message_format",
            field=models.CharField(
                choices=[("text", "Text"), ("html", "HTML"), ("markdown", "Markdown")],
                default="text",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                    ("success", "Success"),
                ],
                default="info",
                max_length=255,
            ),
        ),
    ]
