# Generated by Django 5.2.4 on 2026-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_business_notification_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("push", "Push"),
                    ("sms", "SMS"),
                    ("telegram", "Telegram"),
                    ("all", "All"),
                ],
                default="push",
                max_length=255,
            ),
        ),
    ]
